my:
  greeting: Hello fromn Git 
  name: Arun

db:
  connection:  "{connectionString: 'http://gitrepo1:23now___',userName:'foo',password:'pass'}"
  host: 127.0.0.1
  port: 1200

management.endpoints.web.exposure.include: "*"
